<!DOCTYPE html>
<html lang="en">
    <head>
        <title>surveyengine</title>
        <meta name="keywords" content="" />
		<meta name="description" content="" />
<!-- 
Urbanic Template 
http://www.templatemo.com/preview/templatemo_395_urbanic 
-->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!--<link rel="shortcut icon" href="PUT YOUR FAVICON HERE">-->
        
        <!-- Google Web Font Embed -->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
        
        <!-- Bootstrap core CSS -->
        <link href="/template/css/bootstrap.css" rel='stylesheet' type='text/css'>

        <!-- Custom styles for this template -->
        <link href="/template/js/colorbox/colorbox.css"  rel='stylesheet' type='text/css'>
        <link href="/template/css/templatemo_style.css"  rel='stylesheet' type='text/css'>
        
        <link href="/js/themeroller/jquery-ui.theme.min.css"  rel='stylesheet' type='text/css'>
        <link href="/js/themeroller/jquery-ui.min.css"  rel='stylesheet' type='text/css'>
        <link href="/js/themeroller/jquery-ui.structure.min.css"  rel='stylesheet' type='text/css'>
        
        <link href="/js/bootgrid/jquery.bootgrid.min.css"  rel='stylesheet' type='text/css'>
        <link href="/css/style.css"  rel='stylesheet' type='text/css'>
        
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        
        <script src="/template/js/jquery.min.js" type="text/javascript"></script>
        <script src="/js/jquery-ui.min.js" type="text/javascript"></script>
        <script src="/js/jquery.ui.touch.js" type="text/javascript"></script>
        <script src="/template/js/bootstrap.min.js"  type="text/javascript"></script>
        <script src="/template/js/colorbox/jquery.colorbox-min.js"  type="text/javascript"></script>
        <script src="/js/handlebars-v2.0.0.js"  type="text/javascript"></script>
        <script src="/js/helpers/Helpers.js"  type="text/javascript"></script>
        
        <script src="/js/bootgrid/jquery.bootgrid.min.js"  type="text/javascript"></script>
        <script src="/js/bootgrid/jquery.bootgrid.fa.min.js"  type="text/javascript"></script>
    </head>
    
    <body>

        <div class="templatemo-top-bar" id="templatemo-top" style="background-color:#FFFFD1;padding-bottom:12px;">
            <div class="container">
                <div class="subheader">
                    <div id="email" class="pull-right">
                        <div class="navbar-collapse collapse" id="templatemo-nav-bar">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="active" ><a href="/">HOME</a></li>
                                <li><a href="/surveyengine/survey/add">ADD SURVEY</a></li>
                                <li><a href="/surveyengine/survey/list">SURVEYS</a></li>
                                <li><a  href="#">SCHEDULE EMAIL SURVEY</a></li>
                                <li style="line-height:35px;"><img src="/template/images/email.png" alt="email"/>deanrclow@gmail.com</li>
                            </ul>
                        </div><!--/.nav-collapse -->
                    </div>
                </div>
            </div>
        </div>
        
        <div id="templatemo-contact">
            <div class="container">
                <div class="row" style="margin-top:20px;">
                    <?php echo $this->layout()->content ?>
                </div><!-- /.row -->
            </div><!-- /.container -->
        </div><!-- #templatemo-contact -->

        <div class="templatemo-footer" >
            <div class="container">
                <div class="row">
                    <div class="text-center">

                        <div class="footer_container">
                            <a class="btn btn-lg btn-orange" href="#" role="button" id="btn-back-to-top">Back To Top</a>
                            <div class="height30"></div>
                        </div>
                        <div class="footer_bottom_content">
                        	Copyright © <?php print date("Y"); ?> <a href="http://deanclow.com">deanclow.com</a>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
<!-- templatemo 395 urbanic -->
<!-- 
    Free HTML5 Templates
    http://www.templatemo.com
-->
    </body>
</html>